variables:
  python.version: '3.6'

jobs:
  - job: Update Build Number
    timeoutInMinutes: 5
    pool:
      vmImage: ubuntu-16.04

      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '$(python.version)'
        - script: python version.py
        - bash: echo "##[build.updatebuildnumber]`cat version`"

  - job: Windows
    timeoutInMinutes: 30
    strategy:
      maxParallel: 2
      matrix:
        x64:
          buildArch: x64
        x86:
          buildArch: x86

    pool:
      vmImage: vs2017-win2016

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(buildArch)'
      - script: python version.py
      - powershell: scripts/build.ps1
        displayName: Build
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: out

  - job: macOS
    timeoutInMinutes: 30
    variables:
      buildArch: x64

    pool:
      vmImage: macos-10.13

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(buildArch)'
      - script: python version.py
      - bash: scripts/build.sh
        displayName: Build
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: out

  - job: Linux
    timeoutInMinutes: 30
    strategy:
      maxParallel: 2
      matrix:
        x64:
          buildArch: x64
        x86:
          buildArch: x86

    pool:
      vmImage: ubuntu-16.04

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(buildArch)'
      - script: python version.py
      - bash: scripts/build.sh
        displayName: Build
      - task: PublishPipelineArtifact@0
        inputs:
          targetPath: out